language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
    matrix:
      - PREFER_LOWEST="--prefer-lowest"
      - PREFER_LOWEST=""

matrix:
  allow_failures:
      - php: hhvm

before_script:
    - composer self-update
    - composer update $PREFER_LOWEST

script:
  - vendor/bin/phpunit
